### ISSUE TITLE
Why not use UTF-8 file format

### ISSUE THREAD

**Issue by starit** [AntSharesSDK/antshares-java#1]
When I open this project on macOS, files are loaded into IDE and shows incorrectly.
After I changed file encoding to gb18030, everything is fine.

Why not use UTF-8 as file encoding format ?  As an open source project, this sucks

**Comment by erikzhang** [comment]
You are right, we have change the encoding of all files into utf-8. See commit [78a5005](https://github.com/AntSharesSDK/antshares-java/commit/78a5005a12352207276f41a193f41c0ad7a3d1f2)
